### PR TITLE
Updated semigroupoids dependency

### PR DESCRIPTION
**Pull request by crockeea**

### CODE REVIEW

**Comment by glguy** [comment]
Shouldn't need the _._.1 version bump for the dependency bump

**Comment by crockeea** [comment]
What would you bump it to? My understanding of the [versioning policy](https://wiki.haskell.org/Package_versioning_policy) is that semigroupoids-5.1.* could change the interface, thus breaking this package.

**Comment by glguy** [comment]
This package isn't re-exporting modules from semigroupoids. Also, when Edward's packages depend on other Edward packages they typically only constraint the first version bound. The new upper bound should probably be `< 6`, but Edward can confirm.

**Comment by RyanGlScott** [comment]
We should also bump `comonad` to `< 6` as well.

**Comment by RyanGlScott** [comment]
It looks like this was fixed in 0deac784c85f5fc0a48f9562212313fa204d8107.

**Comment by supki** [comment]
Yeah, somehow I missed this pull request while fixing the bounds here and on Hackage, sorry!

**Pull request closed without merging**
